name: Build and deploy Next.js app to Azure Web App - frontendace

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_605145F5343944F19C45BE218FCB0542 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5CD9BC267C234F6BAA1C24442D44C7C5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2D10C41395014564B775C29F433DBB3B }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t frontendace .
          docker tag frontendace:latest ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/frontendace:latest
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/frontendace:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          app-name: 'frontendace'
          slot-name: 'Production'
          container-registry: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
          container-name: frontendace
          container-tag: latest
          azure-subscription: ${{ secrets.AZURE_SUBSCRIPTION }}
